# Generated by Django 5.1.1 on 2024-10-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikinis', '0002_bikini_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikini',
            name='image',
            field=models.ImageField(upload_to='bikinis_images/'),
        ),
    ]
