# Generated by Django 5.1.1 on 2024-10-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikinis', '0003_alter_bikini_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikini',
            name='image',
            field=models.ImageField(upload_to='bikinis/'),
        ),
    ]
